### ISSUE TITLE
Not working for me in .html files

### ISSUE THREAD

**Issue by opdavies** [MyOutDeskLLC/Tailwind-Formatter#12]
I've installed the plugin and ran `Code > Run Tailwind Formatter` but nothing seems to be happening.

In this example, I've added the `u-bg-blue-550` class at the start of the list, thinking that it would be re-ordered.

```
<legend class="u-bg-blue-550 u-m-0 u-border-0 u-text-base u-font-bold">
```

Are there any additional steps that I need to follow?

**Comment by tance77** [comment]
Currently this plugin does not support custom prefixes like you have in your code. the "u-"

The below code should format as you expect.
```html
<legend class="bg-blue-550 m-0 border-0 text-base font-bold">
```

**Comment by opdavies** [comment]
I see that #13 has just been merged. I'll look forward to re-testing this once the next version is released.
