### ISSUE TITLE
Bad key binding

### ISSUE THREAD

**Issue by nirvdrum** [MyOutDeskLLC/Tailwind-Formatter#15]
The docs say that the keybinding is Ctrl + Shift + H, but the source code has it as [Meta + Shift + H](https://github.com/MyOutDeskLLC/Tailwind-Formatter/blob/5e1af57b7f806c2019c39f6f755f55d3611e98c8/src/main/resources/META-INF/plugin.xml#L13). I don't know if internally the JetBrains IDEs remap that based on platform. On Linux, however, I'm unable to enter the Meta key. I thought that would have remapped to the Windows key, but pressing the Windows key shows up as its own code and I can't combine it with anything else; the best I can do is make it a two stage key sequence.

I've tried to add my own keybinding for Ctrl + Shift + H, but that conflicts with the "Method Hierarchy" and "Shelve Silently" functions and as such, I'm not able to add the keybinding without removing the binding for the other actions. Alt + Shift + H does not conflict with anything and manually adding that binding allows me to invoke the formatter.

**Comment by tance77** [comment]
Have you tried changing it to something else? I can't seem to reproduce the behavior you are describing.

**Comment by nirvdrum** [comment]
I linked to the line in the plugin manifest that shows it's not using the ctrl key, as the README indicates (it says "Hotkey -> Shift + Ctrl + H"). As for the conflicts, are you using macOS? IntelliJ maps some of the keybindings using ctrl to the Apple key on macOS. Otherwise, I'm not sure why you wouldn't see a conflict. I didn't customize either the "Method Hierarchy" or the "Shelve Silently" keybindings. I am using WebStorm, but I don't think those keybindings change across the various IDEs.

As noted, I'm using Alt + Shift + H without incident. But, that was a manual step I needed to take after figuring out why the plugin appeared to not be working. Out of the box, the default keybinding didn't work and the plugin manifest and README are in conflict on what that keybinding should be.

**Comment by tance77** [comment]
These could prove useful. I'm not sure though. Let me know.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/205814429-How-to-enable-meta-key-

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206091279-How-do-you-get-meta-keys-to-work-
