### ISSUE TITLE
Add support for prefixes

### ISSUE THREAD

**Issue by fabrikatdigital** [MyOutDeskLLC/Tailwind-Formatter#20]
Hey,

Very useful plugin, but I would love to see support for prefixes. In the past I have manually added those to the src files and build it again, but it would be nice to have a field for that in the settings.

Thanks!

**Comment by YangAi** [comment]
Looking forward to it. It would be also nice if the plugin could read `tailwind.config.js` and recognize the prefix and other customizations.

Thanks!

**Comment by Winexcel** [comment]
It's really make sense, i hope that author will add this function to the plugin.

Great thanks!
