### ISSUE TITLE
Class autocompletion

### ISSUE THREAD

**Issue by Radiergummi** [MyOutDeskLLC/Tailwind-Formatter#23]
In the GIF on the Readme, you seem to get autocompletion for Tailwind classes. The suggestions don't show up for me though, is there a separate plugin? The Readme doesn't really mention this.

**Comment by WalrusSoup** [comment]
@Radiergummi 

[This is the plugin used.](https://plugins.jetbrains.com/plugin/12074-tailwindcss)
