### ISSUE TITLE
Not working with single quote

### ISSUE THREAD

**Issue by FrancisGregori** [MyOutDeskLLC/Tailwind-Formatter#24]
Since the last update, the formatter doesn't work when the classes are defined with single quotes.

![Example](https://user-images.githubusercontent.com/3008656/82603040-5ad53080-9b88-11ea-989b-083b081baa94.gif)

Plugin version: 1.3.5
Webstorm version: 2020.1.1
Build: WS-201.7223.93

**Comment by tance77** [comment]
Thanks for the bug report Ill def take a look at this as soon as possible.

**Comment by tance77** [comment]
This was fixed in @venyii pull request. Closing this.
