### ISSUE TITLE
Formatting is not applied, if in class attribute are non-standard values

### ISSUE THREAD

**Issue by RuslanZavacky** [MyOutDeskLLC/Tailwind-Formatter#26]
We use this plugin with Ember.js (but I guess it can be any other framework). If we have a variable inside `class` attribute (or interpolation of some sort) formatting is not applied.

Let's take this string for example:

```html
class="flex-wrap relative justify-center -mb-1 stack-gap-1 {{if (eq @variant "vertical") "stack-v" "stack-h"}}"
```

Desired output would be (relative is sorted as 1st, and `{{}}` is kept where it is)

```html
class="relative flex-wrap justify-center -mb-1 stack-gap-1 {{if (eq @variant "vertical") "stack-v" "stack-h"}}"
```

Checked plugin code, thought of contributing, but my Java skills are very much 0 :(

**Comment by shaffe-fr** [comment]
Hi,
I encounter the same problem with Laravel blade templates. Delimiters are `{{ }}` or `@keywork` `@keywork()` `@endkeyword`.
Thanks for the plugin :)

**Comment by WalrusSoup** [comment]
If we can get some working REGEX for blade we can likely detect the extension and support it. but before that, would be pretty difficult to detect which mechanism to use to scan each file.

Will check into it.

**Comment by JesusTheHun** [comment]
The easier would be to let it fully configurable by project. 
Let the user set a list of file extension and its "framework".

```
. jxs => React
.tsx => React TypeScript
.blade.php => Blade
.js => ember.js
```

**Comment by shaffe-fr** [comment]
@WalrusSoup 
Here are the regex used by Laravel to detect delimiters and statements:
```
/(@)?{!!\s*(.+?)\s*!!}(\r?\n)?/s  # For raw echo {!! !!}
/(@)?{{\s*(.+?)\s*}}(\r?\n)?/s    # For regular echoes {{ }}
/(@)?{{{\s*(.+?)\s*}}}(\r?\n)?/s  # For escaped echo {{{ }}}
/\B@(@?\w+(?:::\w+)?)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x  # For other statements like @if @endif...
```
([echoes](https://github.com/laravel/framework/blob/6e563129f679ea0a6fbcb2747e3be77bab3bff1c/src/Illuminate/View/Compilers/Concerns/CompilesEchos.php#L44) and [statements](https://github.com/laravel/framework/blob/6e563129f679ea0a6fbcb2747e3be77bab3bff1c/src/Illuminate/View/Compilers/BladeCompiler.php#L415)).

**Comment by richstandbrook** [comment]
An option to run ordering on selected text would be helpful, then whatever context you're in you could highlight the classes you want sorted and run the command

**Comment by shaffe-fr** [comment]
@richstandbrook that's a great idea, it should be easier to implement 👍
