### ISSUE TITLE
Compatibility with PhpStorm 2020.3 EAP

### ISSUE THREAD

**Issue by vjandrea** [MyOutDeskLLC/Tailwind-Formatter#28]
Hello,
I use PhpStorm 2020.3 EAP, the plugin is listed as incompatible.
If you need a beta tester for the next version, feel free to ping me!

**Comment by shaffe-fr** [comment]
I don't see any hard upper boundary in the code. Maybe the plugin must only be build again?

**Comment by hms** [comment]
Same issue for Rubymine.

**Comment by hms** [comment]
@shaffe-fr where did you see any version requirements in the code?  I looked and didn't see any.

Also, I did see the last build version here is 1.3.5, where as the one I'm running is 1.3.6, which makes one wonder if the source is living somewhere else these days?

**Comment by hms** [comment]
I can confirm that all this requires is a new build -- I downloaded the source locally, built, and then loaded into Rubymine without an issue and it works.

**Comment by ttkoma** [comment]
Same issue for Rider EAP 2020.3 build 203.*

**Comment by shaffe-fr** [comment]
Hi @hms, that's exactly what I tried to say:

>I **don't see** any hard upper boundary in the code. Maybe the plugin must **only be built** again?

I'm glad the fix is that simple, hope that @WalrusSoup will see that.

**Comment by tance77** [comment]
This should be fixed here. https://github.com/MyOutDeskLLC/Tailwind-Formatter/commit/5d88a931dc650973982f553a6fd8ab2455f8c064 

Closing this. :)
