### ISSUE TITLE
No longer working as of WebStorm 2021.1

### ISSUE THREAD

**Issue by sklawren** [MyOutDeskLLC/Tailwind-Formatter#34]
This plugin has stopped working as of WebStorm 2021.1

<img width="750" alt="Screen Shot 2021-04-12 at 15 24 12" src="https://user-images.githubusercontent.com/60169661/114349668-2c4ab480-9ba3-11eb-94fe-a17bdbedf79c.png">

**Comment by heychazza** [comment]
Similar to #33

**Comment by benjamincharity** [comment]
Was pumped to find this as the only non-VSCode user at my current gig. Would love this update!

**Comment by WalrusSoup** [comment]
Released for 2021.1.1
