### ISSUE TITLE
[FEATURE] Add support for running on save

### ISSUE THREAD

**Issue by heychazza** [MyOutDeskLLC/Tailwind-Formatter#38]
Hey guys,

Any chance this could be added with an option to run on save?

**Comment by heychazza** [comment]
Anything? 👀

**Comment by LTroya** [comment]
@heychazza did you find any solution to this?

**Comment by WalrusSoup** [comment]
We're going to deprecate this plugin moving forward, as [automatic class sorting with prettier](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier) is now a first party option for Tailwind, and it has the ability to [format on save](https://www.jetbrains.com/help/idea/prettier.html) natively within Intellij. 

This will be easier to keep up to date as Tailwind continues to add more break-away features in plugins such as forms, typography, etc. It's not feasible for us to pull those in as the JIT compiler now also only outputs classes used, making it hard for us to leverage the same technique to get a sortable class order. Previously @tance77 was actually going through the documentation and doing it by hand.

I realize that's not a solution, but it's simply the more sustainable option for everyone as your stack should be making use of eslint or another code quality tool that integrates with prettier.
