### ISSUE TITLE
PHPStorm 2019.3 compatibility

### ISSUE THREAD

**Issue by ouun** [MyOutDeskLLC/Tailwind-Formatter#4]
I would love to use this but I am not able to install the Plugin. Tried it from the Marketplace within PHPStorm config as well as from disc as package.

However thank you very much for bringing Headspace to PHPStorm. Looks like a neat little helper.

**Comment by WalrusSoup** [comment]
@tance77 You're currently using this with the latest version correct?

**Comment by WalrusSoup** [comment]
This is now out for publishing with the commit 88fbbc1e9671a0038f8ac0b1e54922158ed20bfc

Waiting for Jetbrains approval on this since we made several changes to the build process to make it a bit easier to push these changes out 👍

**Comment by tance77** [comment]
Still broken in latest update. It's targeting the pre-release version 2019.3.1

**Comment by WalrusSoup** [comment]
My error - I assumed that it was going to allow us to use the LATEST-EAP-SNAPSHOT for the current release as that is the default value. That actually targets the next release. For the version I just committed with PR https://github.com/MyOutDeskLLC/Tailwind-Formatter/pull/6 this was adjusted to be the current version available. We'll need to keep a careful eye on this when new releases come out to target this version. However, I do wonder, if the LATEST-EAP-SNAPSHOT applies to the next version to be released officially, does publishing against that mean when that version hits users (2020.1 or 2019.4) it's already available?

**Comment by WalrusSoup** [comment]
This is now approved and listed as an available plugin for 2019.3 in PHPSTORM.

**Comment by IsidroMar95** [comment]
i dont know how to use it, it seems it doesnt work, how this pluging works in phpStorm?
