### ISSUE TITLE
Incompatible since PHPStorm update

### ISSUE THREAD

**Issue by MarioPerini** [MyOutDeskLLC/Tailwind-Formatter#42]
The plugin does not work in the current version of PHPStorm
![image](https://user-images.githubusercontent.com/40631006/127546718-8340d1ab-0717-41bc-b4fb-cd80b4186802.png)

![image](https://user-images.githubusercontent.com/40631006/127546590-4f9bc9c2-0c03-480a-b478-9e2a9b9bf1fc.png)

**Comment by Darmaru** [comment]
#43 Created pull request for this

**Comment by tance77** [comment]
This should be fixed once JetBrains approves the plugin update. Also contains the latest update for all the new tailwindcss 2.2.4 css clases
