### ISSUE TITLE
Failure to build locally

### ISSUE THREAD

**Issue by hms** [MyOutDeskLLC/Tailwind-Formatter#46]
I'd like to attempt some experiments to explore fixes for my environment and suggestions for future enhancements.  I have the latest codebase from master and it does not build.  I get the following error:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/hms/Devel/tailwind-formatter/build.gradle' line: 3

* What went wrong:
An exception occurred applying plugin request [id: 'org.jetbrains.intellij', version: '0.4.13']
> Failed to apply plugin 'org.jetbrains.intellij'.
   > No such property: TEST_COMPILE_CONFIGURATION_NAME for class: org.gradle.api.plugins.JavaPlugin

* How I was building:
grade build --info

Any suggestions?

Thanks

**Comment by tance77** [comment]
Typically intelij has a built in option for all of these runide, build, deploy ect.  Never tried to build through CLI before.

**Comment by hms** [comment]
@tance77 would it be possible to outline the steps you take to do a build.  I'm using Rubymine, one of the Intelij derivatives and don't see a way to build locally.  

And thanks for getting the latest build out so quickly :-)

**Comment by tance77** [comment]
@hms I think it requires you to have IneliJ. There is a community edition you can get for free. It requires Gradle. I'm not really sure if that exists in Rubymine. I've never run it. However in InteliJ there is a grade table you can click in the top right side of the IDE. Once it finishes indexing you should see some things it can do. I attached a screenshot
![Screen Shot 2021-12-06 at 2 58 03 PM](https://user-images.githubusercontent.com/3421501/144936551-6068df88-cd67-4012-b0c9-a94203fa8569.png)
. 

runide will download and install an IDE for you to test and run the plugin.
